image:
- Ubuntu
- Visual Studio 2015

platform:
- x64
- x86
  
configuration:
- Release
- Debug

for:
  -
    matrix:
      only:
        - image: Ubuntu
          platform: x64
          configuration: Release
  
    install:
    - sudo apt-get update
    - sudo apt-get -y install git wget flex bison gperf python3 python3-pip python3-setuptools ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
    - mkdir ~/esp
    - cd ~/esp
    - git clone --recursive https://github.com/espressif/esp-idf.git
    - cd ~/esp/esp-idf
    - ./install.sh esp32
    - . $HOME/esp/esp-idf/export.sh
    - cd ~/projects/socket-sessions
    - git clone https://github.com/gregjesl/macrothreading components/macrothreading

    after_build:
    - idf.py build

before_build:
  - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=%CONFIGURATION%

build_script:
  - cmake --build _builds --config %CONFIGURATION%

test_script:
  - ps: cd _builds
  - ctest -VV -C %CONFIGURATION% --timeout 10