#ifndef BIRCHRIDGE_SOCKET_ERROR_H
#define BIRCHRIDGE_SOCKET_ERROR_H

enum socket_error_enum
{
    SOCKET_OK = 0,
    SOCKET_ERROR_NULL_ARGUEMENT = -1,
    SOCKET_ERROR_INVALID_ARGUEMENT = -2,
    SOCKET_ERROR_BUFFER_OVERFLOW = -3,
    SOCKET_ERROR_BUFFER_UNDERFLOW = -4,
    SOCKET_ERROR_MALLOC_FAIL = -5,
    SOCKET_ERROR_CLOSED = -6,
    SOCKET_ERROR_POLL = -7,
    SOCKET_ERROR_WRITE = -8,
    SOCKET_ERROR_READ = -9,
    SOCKET_ERROR_INVALID_ADDRESS = -10,
    SOCKET_ERROR_CONNECT = -11,
    SOCKET_ERROR_CONFLICT = -12
};

#endif